export enum PourOverStage {
    BLOOMING = 'BLOOMING',
    POURING = 'POURING',
    FIRST_POUR = 'FIRST_POUR',
    SECOND_POUR = 'SECOND_POUR',
    THIRD_POUR = 'THIRD_POUR',
    FOURTH_POUR = 'FOURTH_POUR',
    FIFTH_POUR = 'FIFTH_POUR',
    SIXTH_POUR = 'SIXTH_POUR',
    FINAL = 'FINAL'
}
